name: flutter_template
description: A Flutter template project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=2.8.1'

dependencies:
  flutter:
    sdk: flutter

  # Increase the code-sharing between widgets by removing duplicates
  flutter_hooks: ^0.18.0
  # A state-management library
  hooks_riverpod: ^1.0.1

  # For Networking
  ## A powerful Http client for Dart
  dio: ^4.0.0
  ## A type conversion dio client generator
  retrofit: ^2.2.0

  # Model code generator
  ## Provides Dart Build System builders for handling JSON.
  json_serializable: ^6.2.0
  freezed_annotation: ^0.14.3

  # Data persistence
  shared_preferences: ^2.0.15

  # Small, easy to use and extensible logger
  logger: ^1.1.0

  # Convert between Enum and String
  enum_to_string: ^2.0.1

  # For mocking platform
  platform: ^3.1.0

  # For finding commonly used locations on the filesystem.
  path_provider: ^2.0.11

  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^3.0.6

  tuple: ^2.0.0

  # For Format
  intl: ^0.17.0

  # For Navigation
  auto_route: ^3.2.4
  provider: ^6.0.3

  # UI

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # A Flutter plugin that provides a WebView widget.
  webview_flutter: 2.0.13

  gap: ^2.0.0
  google_fonts: ^2.3.3
  flutter_svg: ^0.22.0
  adaptive_dialog: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.4

  build_runner: ^2.1.11

  # For Networking
  retrofit_generator: ^2.2.0

  # For Assets
  flutter_gen_runner: ^3.1.2

  # For Navigation
  auto_route_generator: ^3.2.3

  # For Analyzer
  effective_dart: ^1.3.2

  # For Model
  freezed: ^0.14.5

  # For Testing
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1

  # For Icon
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/icon-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon-foreground.png" # only available for Android 8.0 devices and above

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svgs/
